version: "3.8"

x-common-variables: &common-variables
  MYSQL_USER: admin
  MYSQL_PASSWORD: admin
  MYSQL_DATABASE: healthservice

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-net
  backend:
    image: areaservice-api
    container_name: areaservice-api
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      <<: *common-variables
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    ports:
      - 8090:8090
    restart: on-failure
    networks:
      - app-net

networks:
  app-net: {}
