version: "3.8"

x-common-variables: &common-variables
  MYSQL_USER: admin
  MYSQL_PASSWORD: admin
  MYSQL_DATABASE: healthservice
  MYSQL_ROOT_PASSWORD: root

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-net

networks:
  app-net: {}
