name: Create Release

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  REGISTRY_TOKEN: ${{ secrets.GHCR_TOKEN }}
  REGISTRY_USERNAME: NithinKuruba

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Login to Github Container Registry
        run: |
          echo "${{ env.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} --username ${{ env.REGISTRY_USERNAME }} --password-stdin

      - id: release
        uses: rymndhng/release-on-push-action@v0.20.0
        with:
          bump_version_scheme: patch

      - name: Check Output Parameters
        run: |
          echo "Tag Name ${{ steps.release.outputs.tag_name }}"
          echo "Version ${{ steps.release.outputs.version }}"
          echo "Revision ${GITHUB_SHA}"
      - name: Set DEPLOY_ID
        run: |
          echo "::set-output name=APP_REVISION::${GITHUB_SHA}"
        id: set-deploy-id

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Area Service UI
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: .
          file: ./ui/Dockerfile
          tags: ${{ env.REGISTRY }}/NithinKuruba/areaservice/areaservice-ui:${{ steps.release.outputs.tag_name }}
          push: true
          build-args: |
            GITHUB_API_TOKEN=${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
            APP_VERSION=${{ steps.release.outputs.version }}
            APP_REVISION=${{ steps.set-deploy-id.outputs.APP_REVISION }}

      - name: Build Area Service API
        uses: docker/build-push-action@v3
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: .
          file: ./api/Dockerfile
          tags: ${{ env.REGISTRY }}/NithinKuruba/areaservice/areaservice-api:${{ steps.release.outputs.tag_name }}
          push: true
          build-args: |
            APP_VERSION=${{ steps.release.outputs.version }}
            APP_REVISION=${{ steps.set-deploy-id.outputs.APP_REVISION }}
